export const GET_PLANTS = "GET_PLANTS"
export const POST_USERDATA = "POST_USERDATA"
export const POST_JSONDATA = "POST_JSONDATA"

//Selectors data
export const GET_HABITAT = "GET_HABITAT"
export const GET_FLOWER_PETAL_COLOR = "GET_FLOWER_PETAL_COLOR"
export const GET_LEAF_BLADE_EDGES = "GET_LEAF_BLADE_EDGES"
export const GET_LEAF_TYPE = "GET_LEAF_TYPE"
export const GET_LEAF_ARRANGEMENT = "GET_LEAF_ARRANGEMENT"
export const GET_COUNTY = "GET_COUNTY"

//Toggle selectors
export const TOGGLE_HABITAT = "TOGGLE_HABITAT"
export const TOGGLE_FLOWER_PETAL_COLOR = "TOGGLE_FLOWER_PETAL_COLOR"
export const TOGGLE_LEAF_BLADE_EDGES = "TOGGLE_LEAF_BLADE_EDGES"
export const TOGGLE_LEAF_TYPE = "TOGGLE_LEAF_TYPE"
export const TOGGLE_LEAF_ARRANGEMENT = "GET_LEAF_ARRANGEMENT"
export const TOGGLE_COUNTY = "TOGGLE_COUNTY"
